# Generated by Django 4.1.5 on 2023-01-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
