# Generated by Django 3.2.9 on 2023-03-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='gave_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='workers_money',
            field=models.IntegerField(default=0),
        ),
    ]
