# Generated by Django 3.2.9 on 2023-02-13 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230212_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='phone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
