# Generated by Django 3.2.9 on 2023-03-04 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230304_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugwork',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
