# Generated by Django 3.2.9 on 2023-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230213_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='category_workers', to='main.WorkCategory'),
        ),
    ]
