# Generated by Django 3.2.9 on 2023-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_workerprofile_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
