# Generated by Django 3.2.9 on 2023-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adminprofile_bugs_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='sent_balance',
            field=models.BooleanField(default=False),
        ),
    ]
