# Generated by Django 3.2.9 on 2023-02-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_adminprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='main.workerprofile'),
        ),
    ]
