# Generated by Django 3.2.9 on 2023-02-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_balancehistory_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='main.workcategory'),
        ),
    ]
